project:
  type: website
  output-dir: docs

website:
  title: "Open Case Studies: The Biology of Ancestry"
  navbar:
    left:
    - text: ""
      href: index.html

format:
  html:
    theme: cosmo
    css: style.css
    toc: true
